### ISSUE TITLE
Feature idea: 1) ESC > Minimize Winbox 2) Double Click title-bar > Full Screen

### ISSUE THREAD

**Issue by 123Peter789** [nextapps-de/winbox#17]
Hi,
its a great tool, I use it already everyday. Implementation was very easy and it works out of the box :)

I catched myself doubleclicking on the title-bar and expecting the winbox to go into fullscreen as well as expecting it to become smaller if its already in fullscreen. Handy would be as well if the ESC-button would minimize the winbox.
Those would be nice features, but really the dot on the i, because its already great. :)

Thank you

**Comment by ts-thomas** [comment]
Hey thanks a lot. The dblclick feature is a really nice suggestion. It is available in the new version 0.1.9. Dispatch the ESC button is probably not a flawless workaround, because this key has a standard behavior in some applications (and also html forms like the select box). I'm thinking about a "minimize all" feature on the bottom right (like windows provide).

**Comment by 123Peter789** [comment]
Awesome, Thanks
