### ISSUE TITLE
Possible to Parent window to communicate with the inner window?

### ISSUE THREAD

**Issue by joshuaquek** [nextapps-de/winbox#2]
Would there be any API / documentation or ability for the parent window to somehow use window.postmessage ( https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage ) or something like that to communicate with the window inside?

**Comment by ts-thomas** [comment]
This should be an option when using `winbox.setUrl(url)`. Because just then it will include an iframe you can communicate with `postMessage`. There are some more options for embedding content, I would say the iframe content strategy is probably the worst of all (but probably also the easiest). So when you like to communicate between both documents, you are still free to do that. I do not know what I could add to the lib for this purpose. All what you need is still existing. When you are not speaking about using URL through an iframe then you can skip the whole `postMessage` part completely and just talk directly between you frames :)
