### ISSUE TITLE
Feature request: Move project to Node 14 and Typescript

### ISSUE THREAD

**Issue by cesco69** [nextapps-de/winbox#38]
I want suggest to move the project to a modern environment like Node 14 and Typescript for help open souce developer to work with Winbox. Currently Winbox "tasks script" aren't compatible with "Node 14" and the absence of typescript make the code obscure.

Bonus suggestion: add "unit test" for check the "pull request".

Thaks for your lib!

**Comment by fzammetti** [comment]
I think all you really need is a type definition file. It shouldn't matter to anyone whether a library you use is written in TS or plain JS, it's going to be JS in the end anyway. But having the type definitions available is nice if your own app is TS-based (like mine is).

**Comment by photonstorm** [comment]
TS Defs are a nice-to-have, for sure. I use Winbox exclusively within TS. But it's absolutely trivial to get by without them. The docs and examples are comprehensive enough and the code is easy to read. TS defs should be a community contribution, it doesn't require recoding the whole lib.

**Comment by fzammetti** [comment]
Hey, look at that, seems it's already available: https://www.typescriptlang.org/dt/search?search=winbox

**Comment by ts-thomas** [comment]
Since JS is a subset of TS I see no need to fully switch to typescript. Also, it does not fit the target audience for such a lib. I make open source software for peoples, which doesn't have the professional skills to do that by themselves. Switching to TS will not make those things better. Also it is a pure web library meant to run in a browser, so that makes JavaScript as the best candidate. I see no advantages in contribution when switching this library from a subset of TS to native TS. That's why type definitions are build for. 

Unfortunately I have not the time to write tests, write type definitions or providing any adapters for React, Angular, VueJS and all others. That should made via contribution. My implementation focus on a solid base which could be simply integrated into __every__ stack. Specific characteristics for specific use cases or environments are left as a task for the developer.
