### ISSUE TITLE
looks great, but what about your promises for flexsearch?

### ISSUE THREAD

**Issue by arete18** [nextapps-de/winbox#4]
This looks like something worth contributing to, but I'm wary of the way you've abandoned your other repos and not kept your promises to the contributors there.

[flexsearch Announcement: New release is coming during Dez 2020] #199
https://github.com/nextapps-de/flexsearch/issues/199

**Comment by ts-thomas** [comment]
Hi, yeah the Flexsearch project eats my time. I also started a full Rust implementation last year and skipped it completely since I recognized that the base code structure needs to be fully re-implemented. A lot of time went into this port, unfortunately.

The WinBox tool is related to a project we are working on in my company. On the other hand, I have to work on Flexsearch in my spare time. I very need some kind of donation support especially for this project, because it is just too large and it needs more time to spent on.

But, the development is actually still in progress. The current state is at the core development. I created ~30 test scenarios which reflects the capability of the search engine (acceptance criteria). Round about the half of them are finished. Probably I will skip some of the "hardcore capability tests" to make a first release earlier.

I will cleanup and merge the dev sources and push the state to a new branch very soon. So everyone can have a look into the progress.
