### ISSUE TITLE
Feature Request: Footer area

### ISSUE THREAD

**Issue by pachacamac** [nextapps-de/winbox#45]
Would it be possible to add an optional footer area? ![here](https://nextapps-de.github.io/winbox/demo/boilerplate.svg) basically where it says `.wb-body{ margin }` in the picture? The use case would be to have a space to easily add additional nav elements or a status bar without having to build a more complicated layout inside the wb-body yourself.

**Comment by ts-thomas** [comment]
Such a footer area is theoretically a part of current `wb-body` (more than a part of the windows border), it just needs the same window background-color to looks like a part of the window, technically we divide `wb-body` into segments. Then we also need to take into account "header" and left/right sidebars, because depending on the scenario the additional nav bar might not being placed at the bottom. Allthough the footer element is probably the most common.

The best is to simply add an wrapper container to the body element of the window which includes the footer (absolute position) and a "new" body (also absolute position) and add `overflow: hidden` to the original window body and add `overflow: auto` to your new body. I will add such a workaround in the documentation (demo page) soon.
